version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      exclude-functions:
        - io.Copy(*bytes.Buffer)
        - (*os.File).Close

    gosec:
      excludes:
        - G104
        - G307

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
